resources:
  - argocd-instance.yaml
  - argocd-cm.yaml

patchesStrategicMerge:
  # Platform
  - resource-customizations/k8s.yaml
  - resource-customizations/openshift.yaml
  - resource-customizations/operators.yaml

  # Platform services
  - resource-customizations/ocs.yaml
  - resource-customizations/kubevirt.yaml
  - resource-customizations/external-secrets.yaml
  
  # Apps
  - resource-customizations/argocd.yaml
  - resource-customizations/rhacm.yaml
  - resource-customizations/rhacs.yaml
  - resource-customizations/cp4i.yaml
  - resource-customizations/cpd.yaml
  - resource-customizations/ansible-automation-platform.yaml
